spring:
  datasource:
    url: jdbc:mysql://192.168.1.104:3306/gmall_pms
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root


dubbo:
  application:
    name: gmall-pms
  registry:
    address: zookeeper://192.168.1.104:2181
  protocol:
    name: dubbo
    port: 20880
  consumer:
    check: false


